version: 2.1

jobs:
  build-and-push:
    docker:
      - image: cimg/base:stable
    steps:
      - setup_remote_docker:
          version: 20.10.11
          docker_layer_caching: true
      - checkout
      - run: docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
      - run: docker buildx build --push -t digitop/t3-app-starter:circleci-v1 .

workflows:
  version: 2
  docker-build-push:
    jobs:
      - build-and-push
