version: 2.1

executors:
  docker-executor:
    docker:
      - image: circleci/python:3.8

jobs:
  build-and-push:
    executor: docker-executor
    steps:
      - checkout

      - setup_remote_docker:
          version: 20.10.7

      - run:
          name: Install Docker Buildx
          command: |
            export DOCKER_CLI_EXPERIMENTAL=enabled
            docker build --platform=local -o . git://github.com/docker/buildx
            mkdir -p ~/.docker/cli-plugins
            mv buildx ~/.docker/cli-plugins/docker-buildx
            docker buildx version

      - run:
          name: Build and Push Docker Image
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

            docker buildx create --use
            docker buildx build --platform linux/amd64,linux/arm64 -t digitop/t3-app-starter:circleci --push .