version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - setup_remote_docker:
          version: 20.10.11
      - checkout
      - run: docker buildx build -t digitop/t3-app-starter:circleci-v1 .

workflows:
  version: 2
  build_and_push:
    jobs:
      - build
